/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.mycompany.crudjdbcdemo.Formularios;

import com.mycompany.crudjdbcdemo.Entidades.CursoAcademico;
import com.mycompany.crudjdbcdemo.controladorDAO.CursoAcademicoDAOimp;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JRadioButtonMenuItem;

/**
 *
 * @author TONY
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public int idCursoAcademico=0;
    public frmMain() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        generaMenuCursosAcademicos();
        //cargaCursoAcademico();
    }
    public void generaMenuCursosAcademicos(){
        
        CursoAcademicoDAOimp cursoaca=CursoAcademicoDAOimp.getInstance();
        
        try{
            List<CursoAcademico> lst=cursoaca.getAll();
            JRadioButtonMenuItem jrcurso;
            ButtonGroup brqCursoAcademico=new ButtonGroup();
            for( CursoAcademico curso :lst){
                jrcurso=new JRadioButtonMenuItem(curso.getDescripcion(), true);
                jrcurso.setName(""+curso.getId());
                if(idCursoAcademico==0){
                    idCursoAcademico=curso.getId();
                }
                jMenuAnoAcademico.add(jrcurso);
                brqCursoAcademico.add(jrcurso);
                
                jrcurso.addItemListener(new ItemListener(){
                    //@Override
                    public void itemStateChanged(ItemEvent e) {
                      JRadioButtonMenuItem jrbSelected=(JRadioButtonMenuItem)e.getItem();
                      idCursoAcademico=Integer.parseInt(jrbSelected.getName());
                      System.out.println(""+idCursoAcademico);  
                    }
                
            });

        }
        }catch(Exception e){
            System.out.println("Error:"+e.getMessage());
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        pnldesktop = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        optMenuCursoAcademico = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        optCurso = new javax.swing.JMenuItem();
        optUnidad = new javax.swing.JMenuItem();
        optAlumno = new javax.swing.JMenuItem();
        optaula = new javax.swing.JMenuItem();
        opmatricula = new javax.swing.JMenuItem();
        opautorizados = new javax.swing.JMenuItem();
        opautorizaciones = new javax.swing.JMenuItem();
        jMenuAnoAcademico = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPersonal = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        optmAcerca = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Parametrizacion");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        optMenuCursoAcademico.setMnemonic('e');
        optMenuCursoAcademico.setText("Mantenimientos");

        cutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("CursoAcademico");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        optMenuCursoAcademico.add(cutMenuItem);

        optCurso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        optCurso.setMnemonic('y');
        optCurso.setText("Curso");
        optCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCursoActionPerformed(evt);
            }
        });
        optMenuCursoAcademico.add(optCurso);

        optUnidad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        optUnidad.setText("Unidad");
        optUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optUnidadActionPerformed(evt);
            }
        });
        optMenuCursoAcademico.add(optUnidad);

        optAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        optAlumno.setMnemonic('p');
        optAlumno.setText("Alumno");
        optAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAlumnoActionPerformed(evt);
            }
        });
        optMenuCursoAcademico.add(optAlumno);

        optaula.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        optaula.setText("Aula");
        optaula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optaulaActionPerformed(evt);
            }
        });
        optMenuCursoAcademico.add(optaula);

        opmatricula.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opmatricula.setText("Matriculas");
        opmatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opmatriculaActionPerformed(evt);
            }
        });
        optMenuCursoAcademico.add(opmatricula);

        opautorizados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opautorizados.setText("Autorizados");
        opautorizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opautorizadosActionPerformed(evt);
            }
        });
        optMenuCursoAcademico.add(opautorizados);

        opautorizaciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opautorizaciones.setText("Autorizaciones");
        opautorizaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opautorizacionesActionPerformed(evt);
            }
        });
        optMenuCursoAcademico.add(opautorizaciones);

        menuBar.add(optMenuCursoAcademico);

        jMenuAnoAcademico.setText("Año Academico");
        menuBar.add(jMenuAnoAcademico);

        jMenu5.setText("Personal");

        jPersonal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jPersonal.setText("Personal");
        jPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPersonalActionPerformed(evt);
            }
        });
        jMenu5.add(jPersonal);

        menuBar.add(jMenu5);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        optmAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        optmAcerca.setMnemonic('a');
        optmAcerca.setText("Acerca de");
        optmAcerca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optmAcercaMouseClicked(evt);
            }
        });
        optmAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmAcercaActionPerformed(evt);
            }
        });
        helpMenu.add(optmAcerca);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnldesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnldesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void optmAcercaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optmAcercaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_optmAcercaMouseClicked

    private void optmAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmAcercaActionPerformed
        // TODO add your handling code here:
        frmAceptarDEDialogo frmacerca=new frmAceptarDEDialogo(this, rootPaneCheckingEnabled);
        frmacerca.setVisible(true);
        
    }//GEN-LAST:event_optmAcercaActionPerformed
    public void cargaCursoAcademico(){
        frmCursoAcademico frmCurso=new frmCursoAcademico();
    
        pnldesktop.add(frmCurso.getLayeredPane());
    }
    public void cargaPersonal(){
         frmPersonal frmpersonal=new frmPersonal();
         
         //pnldesktop.add(frmpersonal.getLayeredPane());
    
    }
    private void optAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAlumnoActionPerformed
        // TODO add your handling code here:
        frmAlumno frmAlum=new frmAlumno();
        frmAlum.setVisible(true);
        
    }//GEN-LAST:event_optAlumnoActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
        frmCursoAcademico frmcursoaca=new frmCursoAcademico();
        frmcursoaca.setVisible(true);
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void optCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCursoActionPerformed
        // TODO add your handling code here:
        frmCurso frmcurso=new frmCurso();
        
        frmcurso.setVisible(true);
        
        
    }//GEN-LAST:event_optCursoActionPerformed

    private void jPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPersonalActionPerformed
        // TODO add your handling code here:
        frmPersonal frmpersonal=new frmPersonal();
        
        frmpersonal.setVisible(true);
    }//GEN-LAST:event_jPersonalActionPerformed

    private void optUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optUnidadActionPerformed
        // TODO add your handling code here:
        frmUnidad frmunidad=new frmUnidad();
        frmunidad.setVisible(true);
    }//GEN-LAST:event_optUnidadActionPerformed

    private void optaulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optaulaActionPerformed
        // TODO add your handling code here:
        frmAula frmaula=new frmAula();
        frmaula.setVisible(true);
    }//GEN-LAST:event_optaulaActionPerformed

    private void opmatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opmatriculaActionPerformed
        // TODO add your handling code here:
        frmMatricula frmmatricula=new frmMatricula();
        frmmatricula.setVisible(true);
    }//GEN-LAST:event_opmatriculaActionPerformed

    private void opautorizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opautorizadosActionPerformed
        // TODO add your handling code here:
        frmAutorizado frmautorizado=new frmAutorizado();
        frmautorizado.setVisible(true);
    }//GEN-LAST:event_opautorizadosActionPerformed

    private void opautorizacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opautorizacionesActionPerformed
        // TODO add your handling code here:
        frmAutorizaciones frmautorizaciones= new frmAutorizaciones();
        frmautorizaciones.setVisible(true);
    }//GEN-LAST:event_opautorizacionesActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenuAnoAcademico;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jPersonal;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem opautorizaciones;
    private javax.swing.JMenuItem opautorizados;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem opmatricula;
    private javax.swing.JMenuItem optAlumno;
    private javax.swing.JMenuItem optCurso;
    private javax.swing.JMenu optMenuCursoAcademico;
    private javax.swing.JMenuItem optUnidad;
    private javax.swing.JMenuItem optaula;
    private javax.swing.JMenuItem optmAcerca;
    private javax.swing.JDesktopPane pnldesktop;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
