/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.crudjdbcdemo.Formularios;

import com.mycompany.crudjdbcdemo.Entidades.Personal;
import com.mycompany.crudjdbcdemo.controladorDAO.PersonalDaoimp;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author TONY
 */
public class frmPersonal extends javax.swing.JFrame {

    /**
     * Creates new form Personal
     */
    public frmPersonal() {
        initComponents();
        configTabla();
        cargaTabla();
         
    }
    
    private void configTabla(){
        String col[]={"ID","DNI","NOMBRE","APELLIDO1","APELLIDO2","DIRECCION","CP","POBLACION","PROVINCIA","TELEFONO","EMAIL","TIPO"};
        
        DefaultTableModel modelo=new DefaultTableModel(col,0){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
    };
        jtPersonal.setModel(modelo);
    }
    
    private void cargaTabla(){
        DefaultTableModel modelo=(DefaultTableModel)jtPersonal.getModel();
        
        PersonalDaoimp per=PersonalDaoimp.getInstance();
        String[] fila=new String[12];
        
        modelo.setNumRows(0);
        try{
           List<Personal>lst=per.getAll();
            
            for(Personal curso :lst){
                fila[0]=""+curso.getId();
                fila[1]=""+curso.getDni();
                fila[2]=""+curso.getNombre();
                fila[3]=""+curso.getApellido1();
                fila[4]=""+curso.getApellido2();
                fila[5]=""+curso.getDireccion();
                fila[6]=""+curso.getCp();
                fila[7]=""+curso.getPoblacion();
                fila[8]=""+curso.getProvincia();
                fila[9]=""+curso.getTelefono();
                fila[10]=""+curso.getEmail();
                fila[11]=""+curso.getTipo();
                modelo.addRow(fila);
            }
            
            
        }catch(Exception e){
            System.out.println("Error:"+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jtPersonal = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(0, 255, 255));

        jtPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "dni", "nombre", "apellido1", "apellido2", "direccion", "cp", "poblacion", "provincia", "telefono", "email", "tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPersonalMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtPersonal);

        btnadd.setText("Añadir");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnborrar.setText("Borrar");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnadd)
                .addGap(58, 58, 58)
                .addComponent(btnborrar)
                .addGap(166, 166, 166)
                .addComponent(txtbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd)
                    .addComponent(btnborrar)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            System.out.println("pulsado enter");
            DefaultTableModel modelo=(DefaultTableModel) jtPersonal.getModel();
            TableRowSorter <TableModel> trSorter=new TableRowSorter<TableModel>(modelo);
            
            jtPersonal.setRowSorter(trSorter);
            
            if(txtbuscar.getText().length()==0){
                trSorter.setRowFilter(null);
            }else{
                trSorter.setRowFilter(RowFilter.regexFilter(txtbuscar.getText().trim()));
            }
        }
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
            JDialog frame =new JDialog();
            frame.setTitle("Detalle añadir Personal");
            frame.setModal(true);
            jpPersonalAdd panel=new jpPersonalAdd();
            

            frame.getContentPane().add(panel);
            frame.pack();

            frame.setVisible(true); 
            cargaTabla();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        // TODO add your handling code here:
        PersonalDaoimp per=PersonalDaoimp.getInstance();
        try{
            int i =Integer.parseInt((jtPersonal.getValueAt(jtPersonal.getSelectedRow(), 0)).toString());
            per.delete(i);
            JOptionPane.showMessageDialog(this, "Personal eliminado correctamente");
            cargaTabla();
        }catch(Exception e){
            System.out.println("Error:"+e.getMessage());
         } 
    }//GEN-LAST:event_btnborrarActionPerformed

    private void jtPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPersonalMouseClicked
        // TODO add your handling code here:
         if(evt.getClickCount()==2){
            JDialog frame =new JDialog();
            frame.setTitle("Detalle Personal");
            frame.setModal(true);
            jpPersonalUpdate panel=new jpPersonalUpdate();
            int idSeleccion=Integer.parseInt(jtPersonal.getValueAt(jtPersonal.getSelectedRow(), 0).toString());
            panel.PersonalCargaDetalle(idSeleccion);

            frame.getContentPane().add(panel);
            frame.pack();

            frame.setVisible(true);
            cargaTabla();

        }
    }//GEN-LAST:event_jtPersonalMouseClicked

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnborrar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtPersonal;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
